# -----------------------------
# SERVIDOR
# -----------------------------
# (Opcional, por defecto es 8080)
server.port=8080

# -----------------------------
# DATOS EN MEMORIA (H2) me toca instalar postgres y remplzar desde las 10 hasta la 13 que son lso datos 
# -----------------------------
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/seguimiento_tiempo
spring.datasource.username=app_user
spring.datasource.password=ADMIN123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#--spring.h2.console.enabled=true

# Que Spring JPA cree/actualice tablas según tus entidades
##spring.jpa.hibernate.ddl-auto=update
##cometar la linea 19
#spring.jpa.hibernate.ddl-auto=create-drop

##spring.jpa.properties.hibernate.format_sql=true
## toca descargar dbaver postgres
## eliminar el iniciador datalinitializer 
## tengo que crear el script de la clase tarea 
## cambiar el controlador get para hacerlo com ocaht nos dijo panel controller
## ya toca comenzar el angular en servicio
## toca eliminar las clases de las tablas creadas- con el viejito
# Mostrar SQL en consola (opcional)
spring.jpa.show-sql=true

# -----------------------------
# CREDENCIALES DEL ADMIN
# -----------------------------
# Usados por DataInitializer para crear el usuario admin
app.admin.username=admin
app.admin.password=admin123
app.admin.roles=ADMIN


# Clave secreta para firmar los JWT (pon aquí un valor lo bastante largo y aleatorio)
jwt.secret=TuClaveSuperSecretaQueDebeSerMuyLargaYSegura123456

# Tiempo de expiración en milisegundos (1 hora = 60 * 60 * 1000 = 3600000)
jwt.expiration=3600000